### ISSUE TITLE
Function HasHeader() checks for field named "header" instead of a field of type "Header"

### ISSUE THREAD

**Issue by kodie-artner** [ros-tooling/libstatistics_collector#51]
## Description
In received_message_age.hpp, the HasHeader() function checks if the msg contains a field "header". In this situation one cannot have a custom message custom/Header and call the field "header" in other messages. It should instead check if the message contains a field "header" with type "Header"

### Expected Behavior
Return  true if a message contains a field named "header" with type "Header" (for foxy, . 

### Actual Behavior
Returns true if a message contains a field named "header" regardless of the type.

## System (please complete the following information)
 - OS: Ubuntu 20.04
 - ROS 2 Distro: Foxy

** For ROS 2 bugs - please attach a VCS.repos or Dockerfile if possible to help us reproduce the environment **

## Additional context
** Add any other context about the problem here **

**Comment by emersonknapp** [comment]
Thanks for the report! This does indeed sound like a problem - prs always welcome of course if you have an idea how to fix it :)

**Comment by kodie-artner** [comment]
I was a bit hesitant to make a pr because I don't have too much experience with c++ but I can give it a try!

**Comment by technixol** [comment]
Is this issue still being tackled? I kept receiving compilation errors because a field in my custom message definition is named "header" and I believe the compiler was trying to use my message type instead of std_msgs/msg/Header when calling HasHeader(). I think this is the case because the error explained that the compiler kept trying to find "m.header.stamp" in my message definition instead of the std_msg's header definition because "stamp" is not a subfield of my header field.

**Comment by kodie-artner** [comment]
It became a bit of an rabbit hole changing it to look for a msg of type std_msgs/msg/Header because some tests made up different header msgs and didn't want to depend on std_msgs.

**Comment by Timple** [comment]
So I ran into this issue today. Still valid!
